import {
  HOME_HERO_BANNER_IMAGE1,
  HOME_HERO_BANNER_IMAGE2,
  HOME_HERO_BANNER_IMAGE3,
  HOME_HERO_BANNER_IMAGE4,
  HOME_HERO_ABOUT_IMAGE1,
  HOME_HERO_ABOUT_IMAGE2,
  HOME_HERO_ABOUT_IMAGE3,
  HOME_HERO_ABOUT_IMAGE4,
} from "@assets/index";
import {} from "@assets/index";

export const images = [
  HOME_HERO_BANNER_IMAGE1,
  HOME_HERO_BANNER_IMAGE2,
  HOME_HERO_BANNER_IMAGE3,
  HOME_HERO_BANNER_IMAGE4,
];
export const aboutImages = [
  HOME_HERO_ABOUT_IMAGE1,
  HOME_HERO_ABOUT_IMAGE2,
  HOME_HERO_ABOUT_IMAGE3,
  HOME_HERO_ABOUT_IMAGE4,
];


